<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ShippingController;
use App\Http\Controllers\Admin\TaxonomyController;
use App\Http\Controllers\Admin\TicketController as AdminTicketController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FavoriteController;
use App\Http\Controllers\OrderTrackingController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Route;

Route::get('/', [StoreController::class, 'home'])->name('home');
Route::get('/shop', [StoreController::class, 'shop'])->name('shop');
Route::get('/search/products', [StoreController::class, 'searchProducts'])->name('products.search');
Route::get('/categories/{category:slug}', [StoreController::class, 'category'])->name('categories.show');
Route::get('/products/{product:slug}', [StoreController::class, 'product'])->name('products.show');
Route::get('/product-images/{filename}', [ProductController::class, 'image'])->where('filename', '[A-Za-z0-9._-]+')->name('product-images.show');
Route::get('/articles', [StoreController::class, 'articles'])->name('articles.index');
Route::get('/tags/{tag:slug}', [StoreController::class, 'tag'])->name('tags.show');
Route::get('/articles/tags/{tag:slug}', [StoreController::class, 'tag']);
Route::get('/articles/categories/{articleCategory:slug}', [StoreController::class, 'articleCategory'])->name('article-categories.show');
Route::get('/articles/{article:slug}', [StoreController::class, 'article'])->name('articles.show');
Route::get('/sitemap.xml', SitemapController::class)->name('sitemap');
Route::get('/about-us', [StoreController::class, 'page'])->defaults('page', 'about')->name('about');
Route::get('/contact-us', [StoreController::class, 'page'])->defaults('page', 'contact')->name('contact');
Route::post('/contact-us', ContactController::class)->middleware('throttle:5,1')->name('contact.store');
Route::get('/terms', [StoreController::class, 'page'])->defaults('page', 'terms')->name('terms');
Route::get('/orders/{order}/invoice/{token}', [CheckoutController::class, 'invoice'])->name('orders.invoice');
Route::get('/orders/{order}/invoice/{token}/pdf', [CheckoutController::class, 'invoicePdf'])->name('orders.invoice.pdf');
Route::get('/payments/zarinpal/callback/{order}/{token}', [CheckoutController::class, 'callback'])->name('payments.zarinpal.callback');
Route::get('/track-order', OrderTrackingController::class)->middleware('throttle:20,1')->name('orders.track');
Route::middleware('auth')->group(function () {
    Route::get('/checkout', [StoreController::class, 'checkout'])->name('checkout');
    Route::post('/checkout', [CheckoutController::class, 'store'])->middleware('throttle:10,1')->name('checkout.store');
    Route::get('/account', [StoreController::class, 'account'])->name('account');
    Route::patch('/account/profile', [AccountController::class, 'update'])->name('account.profile.update');
    Route::post('/favorites/{product}', [FavoriteController::class, 'toggle'])->name('favorites.toggle');
    Route::get('/tickets', [TicketController::class, 'index'])->name('tickets.index');
    Route::post('/tickets', [TicketController::class, 'store'])->middleware('throttle:10,1')->name('tickets.store');
    Route::get('/tickets/{ticket}', [TicketController::class, 'show'])->name('tickets.show');
    Route::post('/tickets/{ticket}/reply', [TicketController::class, 'reply'])->middleware('throttle:20,1')->name('tickets.reply');
    Route::patch('/tickets/{ticket}/close', [TicketController::class, 'close'])->name('tickets.close');

    Route::middleware('can:manage-store')->group(function () {
        Route::get('/admin', [StoreController::class, 'admin'])->name('admin');
        Route::post('/admin/products', [ProductController::class, 'store'])->name('admin.products.store');
        Route::post('/admin/products/{product}/images', [ProductController::class, 'storeImage'])->name('admin.products.images.store');
        Route::get('/admin/products/{product}', [ProductController::class, 'show'])->name('admin.products.show');
        Route::patch('/admin/products/{product}', [ProductController::class, 'update'])->name('admin.products.update');
        Route::delete('/admin/products/{product}', [ProductController::class, 'destroy'])->name('admin.products.destroy');
        Route::post('/admin/articles', [ArticleController::class, 'store'])->name('admin.articles.store');
        Route::patch('/admin/articles/{article}', [ArticleController::class, 'update'])->name('admin.articles.update');
        Route::delete('/admin/articles/{article}', [ArticleController::class, 'destroy'])->name('admin.articles.destroy');
        Route::patch('/admin/tags/{tag}', [TaxonomyController::class, 'updateTag'])->name('admin.tags.update');
        Route::delete('/admin/tags/{tag}', [TaxonomyController::class, 'destroyTag'])->name('admin.tags.destroy');
        Route::patch('/admin/article-categories/{articleCategory}', [TaxonomyController::class, 'updateArticleCategory'])->name('admin.article-categories.update');
        Route::delete('/admin/article-categories/{articleCategory}', [TaxonomyController::class, 'destroyArticleCategory'])->name('admin.article-categories.destroy');
        Route::put('/admin/shipping', [ShippingController::class, 'update'])->name('admin.shipping.update');
        Route::get('/admin/orders', [OrderController::class, 'index'])->name('admin.orders.index');
        Route::post('/admin/orders', [OrderController::class, 'store'])->name('admin.orders.store');
        Route::get('/admin/users', [AdminUserController::class, 'index'])->name('admin.users.index');
        Route::get('/admin/orders/{order}', [OrderController::class, 'show'])->name('admin.orders.show');
        Route::patch('/admin/orders/{order}/status', [OrderController::class, 'updateStatus'])->name('admin.orders.status');
        Route::get('/admin/orders/{order}/receipt', [OrderController::class, 'receipt'])->name('admin.orders.receipt');
        Route::get('/admin/tickets', [AdminTicketController::class, 'index'])->name('admin.tickets.index');
        Route::get('/admin/tickets/{ticket}', [AdminTicketController::class, 'show'])->name('admin.tickets.show');
        Route::post('/admin/tickets/{ticket}/reply', [AdminTicketController::class, 'reply'])->middleware('throttle:30,1')->name('admin.tickets.reply');
        Route::patch('/admin/tickets/{ticket}/close', [AdminTicketController::class, 'close'])->name('admin.tickets.close');
    });
});
require __DIR__.'/auth.php';
