<?php
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ShippingController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\OrderTrackingController;
use Illuminate\Support\Facades\Route;
Route::get('/',[StoreController::class,'home'])->name('home');
Route::get('/shop',[StoreController::class,'shop'])->name('shop');
Route::get('/products/{product:slug}',[StoreController::class,'product'])->name('products.show');
Route::get('/articles',[StoreController::class,'articles'])->name('articles.index');
Route::get('/articles/{article:slug}',[StoreController::class,'article'])->name('articles.show');
Route::get('/about-us',[StoreController::class,'page'])->defaults('page','about')->name('about');
Route::get('/contact-us',[StoreController::class,'page'])->defaults('page','contact')->name('contact');
Route::get('/terms',[StoreController::class,'page'])->defaults('page','terms')->name('terms');
Route::get('/checkout',[StoreController::class,'checkout'])->name('checkout');
Route::post('/checkout',[CheckoutController::class,'store'])->middleware('throttle:10,1')->name('checkout.store');
Route::get('/orders/{order}/invoice/{token}',[CheckoutController::class,'invoice'])->name('orders.invoice');
Route::get('/orders/{order}/invoice/{token}/pdf',[CheckoutController::class,'invoicePdf'])->name('orders.invoice.pdf');
Route::get('/payments/zarinpal/callback/{order}/{token}',[CheckoutController::class,'callback'])->name('payments.zarinpal.callback');
Route::get('/track-order',OrderTrackingController::class)->middleware('throttle:20,1')->name('orders.track');
Route::middleware('auth')->group(function(){Route::get('/account',[StoreController::class,'account'])->name('account');Route::patch('/account/profile',[AccountController::class,'update'])->name('account.profile.update');Route::middleware('can:manage-store')->group(function(){Route::get('/admin',[StoreController::class,'admin'])->name('admin');Route::post('/admin/products',[ProductController::class,'store'])->name('admin.products.store');Route::patch('/admin/products/{product}',[ProductController::class,'update'])->name('admin.products.update');Route::delete('/admin/products/{product}',[ProductController::class,'destroy'])->name('admin.products.destroy');Route::post('/admin/articles',[ArticleController::class,'store'])->name('admin.articles.store');Route::patch('/admin/articles/{article}',[ArticleController::class,'update'])->name('admin.articles.update');Route::delete('/admin/articles/{article}',[ArticleController::class,'destroy'])->name('admin.articles.destroy');Route::put('/admin/shipping',[ShippingController::class,'update'])->name('admin.shipping.update');Route::patch('/admin/orders/{order}/status',[OrderController::class,'updateStatus'])->name('admin.orders.status');Route::get('/admin/orders/{order}/receipt',[OrderController::class,'receipt'])->name('admin.orders.receipt');});});
require __DIR__.'/auth.php';
