import { Head, Link } from '@inertiajs/react';
import { useMemo, useState } from 'react';

type Product={id:number;name:string;price:number;sale?:number;brand:string;color:string;image:string;stock:boolean;tag?:string};
const fallback:Product[]=[
 {id:1,name:'ایرپاد پرو نسل ۲',price:6800000,sale:5990000,brand:'Apple',color:'سفید',stock:true,tag:'۲۵٪ تخفیف',image:'https://images.unsplash.com/photo-1606741965429-69c23a05a15c?auto=format&fit=crop&w=700&q=80'},
 {id:2,name:'هندزفری گردنی Level U2',price:1890000,brand:'Samsung',color:'مشکی',stock:true,image:'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=700&q=80'},
 {id:3,name:'شارژر ۲۵ وات سامسونگ',price:990000,sale:850000,brand:'Samsung',color:'سفید',stock:true,tag:'پرفروش',image:'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=700&q=80'},
 {id:4,name:'قاب شفاف آیفون ۱۵',price:420000,brand:'Nillkin',color:'شفاف',stock:false,image:'https://images.unsplash.com/photo-1603899122634-f086ca5f5ddd?auto=format&fit=crop&w=700&q=80'}
];
const toman=(n:number)=>new Intl.NumberFormat('fa-IR').format(n)+' تومان';
export default function Storefront({view='home',products,auth}:any){
 const [search,setSearch]=useState(''); const [cart,setCart]=useState<Product[]>([]); const [fav,setFav]=useState<number[]>([]); const [panel,setPanel]=useState<'cart'|'account'|null>(null); const [filter,setFilter]=useState(''); const [menuOpen,setMenuOpen]=useState(false);
 const list:Product[]=(Array.isArray(products)?products:products?.data||fallback).map((p:any,i:number)=>({id:p.id||fallback[i]?.id||i+1,name:p.name||fallback[i]?.name,price:Number(p.price||fallback[i]?.price),sale:p.sale_price?Number(p.sale_price):fallback[i]?.sale,brand:p.brand?.name||fallback[i]?.brand||'Apple',color:p.attributes?.color||fallback[i]?.color||'مشکی',stock:p.stock!==undefined?p.stock>0:fallback[i]?.stock,image:p.main_image||fallback[i]?.image||fallback[0].image}));
 const displayed=useMemo(()=>list.filter(p=>p.name.includes(search)||p.brand.toLowerCase().includes(search.toLowerCase())).filter(p=>!filter||(filter==='sale'?!!p.sale:filter==='stock'?p.stock:p.brand===filter)),[list,search,filter]);
 const add=(p:Product)=>setCart(c=>[...c,p]);
 const section=view==='shop'?'فروشگاه':view==='articles'?'مجله ایرگجت':view==='admin'?'مدیریت فروشگاه':view==='account'?'حساب کاربری':view==='checkout'?'تکمیل سفارش':'';
 return <><Head title={section||'ایرگجت | لوازم جانبی موبایل'}><meta name="description" content="خرید مطمئن لوازم جانبی موبایل، ایرپاد و گجت با ارسال سریع" /></Head><div className="site" dir="rtl">
 <div className="topbar"><span>ارسال رایگان برای سفارش‌های بالای ۲ میلیون تومان</span><span>پشتیبانی: ۰۵۱-۳۷۶۵۰۰۰۰</span></div>
 <header><Link href="/" className="logo" aria-label="ایرگجت">air<span>gadget</span><b>●</b></Link><nav className={menuOpen?'open':''}><Link href="/shop">فروشگاه</Link><Link href="/articles">مجله</Link><Link href="/about-us">درباره ما</Link><Link href="/contact-us">تماس با ما</Link></nav><div className="head-actions"><button className="icon account-icon" aria-label="حساب کاربری" onClick={()=>setPanel('account')}>◎</button><button className="icon basket" aria-label="سبد خرید" onClick={()=>setPanel('cart')}>▱<i>{cart.length}</i></button><button className="icon menu-toggle" aria-label="نمایش منو" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>☰</button></div></header>
 <div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} aria-label="جست‌وجوی محصولات" placeholder="جست‌وجو در میان محصولات و برندها..."/><button onClick={()=>document.querySelector('.products')?.scrollIntoView({behavior:'smooth'})}>جست‌وجو</button></div>
 {view==='home'&&<><main className="hero"><div><em>تجربه‌ای متفاوت از تکنولوژی</em><h1>گجت‌های کوچک،<br/><strong>لذت‌های بزرگ</strong></h1><p>جدیدترین لوازم جانبی موبایل و ایرپاد را با تضمین اصالت و ارسال سریع تهیه کنید.</p><Link className="primary" href="/shop">مشاهده فروشگاه ←</Link></div><div className="hero-art"><div className="orb"></div><img src="https://images.unsplash.com/photo-1606741965429-69c23a05a15c?auto=format&fit=crop&w=900&q=85"/><span className="float-card">✓ تضمین اصالت کالا</span><span className="float-sale">تا ۴۰٪<small>تخفیف</small></span></div></main>
 <section className="benefits"><div>⚡ <b>ارسال سریع</b><small>تحویل در سریع‌ترین زمان</small></div><div>◈ <b>ضمانت اصالت</b><small>کالای اورجینال و باکیفیت</small></div><div>↻ <b>۷ روز ضمانت بازگشت</b><small>خریدی مطمئن و آسان</small></div><div>☏ <b>پشتیبانی واقعی</b><small>هر روز هفته کنار شما</small></div></section>
 <CategoryCards/></>}
 {view==='articles'?<Articles/>:view==='admin'?<Admin/>:view==='account'?<Account/>:view==='checkout'?<Checkout cart={cart}/>:view==='about'||view==='contact'||view==='terms'?<StaticPage type={view}/>:<section className="products"><div className="section-title"><div><em>{view==='shop'?'کالای مورد علاقه‌تان را پیدا کنید':'تازه از راه رسیده'}</em><h2>{view==='shop'?'همه محصولات':'آخرین محصولات'}</h2></div>{view==='shop'&&<div className="filters">{[['','همه'],['sale','تخفیف‌دار'],['stock','موجود'],['Apple','Apple'],['Samsung','Samsung']].map(([value,label])=><button className={filter===value?'active':''} onClick={()=>setFilter(value)} key={value}>{label}</button>)}</div>}<Link href="/shop">مشاهده همه ←</Link></div>{displayed.length?<div className="product-grid">{displayed.map(p=><ProductCard key={p.id} p={p} add={add} fav={fav.includes(p.id)} toggle={()=>setFav(f=>f.includes(p.id)?f.filter(x=>x!==p.id):[...f,p.id])}/>)}</div>:<div className="no-results"><b>محصولی پیدا نشد</b><span>عبارت جست‌وجو یا فیلترها را تغییر دهید.</span></div>}</section>}
 {view==='home'&&<section className="promo"><div><em>پیشنهاد ویژه امروز</em><h2>صدایی که می‌خواهید<br/>بشنوید.</h2><p>ایرپاد پرو با حذف نویز فعال، فقط تا پایان امروز.</p><Link href="/shop" className="light-button">مشاهده پیشنهاد</Link></div><span>airpods<br/><b>pro</b></span></section>}
 <footer><div className="logo">air<span>gadget</span><b>●</b></div><p>مرجع خرید حرفه‌ای لوازم جانبی و گجت‌های هوشمند.</p><div className="footerlinks"><Link href="/terms">قوانین و مقررات</Link><Link href="/contact-us">تماس با ما</Link><Link href="/about-us">درباره ما</Link></div></footer>
 {panel&&<button className="drawer-backdrop" aria-label="بستن پنل" onClick={()=>setPanel(null)}/>}
 {panel==='cart'&&<aside className="drawer"><button className="close" aria-label="بستن" onClick={()=>setPanel(null)}>×</button><h2>سبد خرید شما</h2>{cart.length?<>{cart.map((p,i)=><div className="cart-item" key={i}><img src={p.image} alt=""/><span>{p.name}<small>{toman(p.sale||p.price)}</small></span><button aria-label={`حذف ${p.name}`} onClick={()=>setCart(c=>c.filter((_,x)=>x!==i))}>×</button></div>)}<div className="total">جمع کل <b>{toman(cart.reduce((s,p)=>s+(p.sale||p.price),0))}</b></div><Link className="primary full" href="/checkout">ادامه و پرداخت</Link></>:<p className="empty">سبد خرید شما خالی است.</p>}</aside>}
 {panel==='account'&&<aside className="drawer"><button className="close" aria-label="بستن" onClick={()=>setPanel(null)}>×</button><h2>حساب کاربری</h2>{auth?.user?<><p>{auth.user.first_name} عزیز، خوش آمدید.</p><Link className="primary full" href={auth.user.is_admin?'/admin':'/account'}>{auth.user.is_admin?'ورود به پنل مدیریت':'مشاهده حساب کاربری'}</Link></>:<><p>برای مشاهده سفارش‌ها، آدرس‌ها و علاقه‌مندی‌ها وارد حساب خود شوید.</p><Link className="primary full" href="/login">ورود / ثبت‌نام</Link></>}</aside>}
 </div></>}
function ProductCard({p,add,fav,toggle}:any){return <article className="card"><div className="photo">{p.sale&&<span className="badge">{p.tag||'تخفیف ویژه'}</span>}<button className="heart" aria-label="افزودن به علاقه‌مندی" onClick={toggle}>{fav?'♥':'♡'}</button><img src={p.image} alt={p.name} loading="lazy"/>{!p.stock&&<span className="out">ناموجود</span>}</div><div className="card-body"><small>{p.brand}</small><h3>{p.name}</h3><div>{p.sale&&<del>{toman(p.price)}</del>}<b>{toman(p.sale||p.price)}</b><button disabled={!p.stock} aria-label={`افزودن ${p.name} به سبد`} onClick={()=>add(p)}>+</button></div></div></article>}
function CategoryCards(){return <section className="categories"><div className="section-title"><div><em>دسته‌بندی‌ها</em><h2>هر چه نیاز دارید</h2></div></div><div className="category-grid">{[['🎧','ایرپاد و هندزفری','۸۴ محصول'],['⚡','شارژر و کابل','۱۲۰ محصول'],['📱','قاب و محافظ','۲۷۰ محصول'],['⌚','گجت هوشمند','۵۲ محصول']].map(x=><Link href="/shop" key={x[1]}><i>{x[0]}</i><b>{x[1]}</b><small>{x[2]} ←</small></Link>)}</div></section>}
function Articles(){return <main className="page"><em>راهنما و بررسی تخصصی</em><h1>مجله ایرگجت</h1><div className="article-grid">{[['راهنمای خرید بهترین ایرپاد برای ورزش','راهنمای خرید','https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=700&q=80'],['۵ روش افزایش عمر باتری گوشی','آموزش','https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=700&q=80'],['مقایسه شارژرهای GaN و معمولی','بررسی تخصصی','https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=700&q=80']].map(a=><article className="article" key={a[0]}><img src={a[2]} alt="" loading="lazy"/><small>{a[1]}</small><h2>{a[0]}</h2><p>نکات کاربردی و اطلاعات دقیق برای انتخاب بهتر لوازم جانبی.</p><a>ادامه مطلب ←</a></article>)}</div></main>}
function StaticPage({type}:any){const data:any={about:['درباره ایرگجت','ایرگجت از سال ۱۴۰۰ با هدف آسان‌تر کردن خرید کالای دیجیتال آغاز به کار کرد. ما کیفیت، اصالت و رضایت شما را در اولویت قرار می‌دهیم.'],contact:['تماس با ما','مشهد، بلوار سجاد · تلفن: ۰۵۱-۳۷۶۵۰۰۰۰ · پشتیبانی: support@airgadget.ir'],terms:['قوانین و مقررات','ثبت سفارش به منزله پذیرش قوانین فروشگاه است. امکان بازگشت کالا مطابق قوانین تجارت الکترونیک و شرایط هر محصول فراهم است.']};return <main className="page static"><em>AirGadget</em><h1>{data[type][0]}</h1><p>{data[type][1]}</p>{type==='contact'&&<form><input placeholder="نام و نام خانوادگی"/><input placeholder="شماره تماس"/><textarea placeholder="پیام شما"/><button className="primary">ارسال پیام</button></form>}</main>}
function Account(){return <main className="page account"><h1>حساب کاربری من</h1><div className="account-grid"><aside><b>داشبورد</b><a>سفارش‌های من</a><a>آدرس‌ها</a><a>علاقه‌مندی‌ها</a><a>جزئیات حساب</a></aside><section><h2>سلام، کاربر عزیز 👋</h2><p>از این بخش می‌توانید سفارش‌ها، آدرس‌ها و فاکتورهای PDF خود را مدیریت کنید.</p><div className="stats"><b>۰<small>سفارش</small></b><b>۰<small>علاقه‌مندی</small></b><b>۰<small>آدرس</small></b></div></section></div></main>}
function Checkout({cart}:any){return <main className="page checkout"><h1>تکمیل سفارش</h1><div className="checkout-grid"><form><h3>روش ارسال</h3><label><input type="radio" name="ship" defaultChecked/> پیک شهری مشهد</label><label><input type="radio" name="ship"/> دریافت حضوری</label><label><input type="radio" name="ship"/> پست پیشتاز (هزینه از پنل مدیریت)</label><h3>روش پرداخت</h3><label><input type="radio" name="pay" defaultChecked/> پرداخت آنلاین زرین‌پال</label><label><input type="radio" name="pay"/> کارت به کارت و ارسال تصویر رسید</label><input placeholder="آدرس کامل"/><button className="primary">ثبت سفارش</button></form><aside><h3>خلاصه سفارش</h3><p>{cart.length} کالا در سبد شما</p><b>{toman(cart.reduce((s:any,p:any)=>s+(p.sale||p.price),0))}</b></aside></div></main>}
function Admin(){return <main className="page admin"><h1>پنل مدیریت</h1><div className="dashboard"><div><b>۱۲۴,۸۰۰,۰۰۰</b><small>درآمد این ماه</small></div><div><b>۴۸</b><small>تعداد سفارش‌ها</small></div><div><b>۲,۶۰۰,۰۰۰</b><small>میانگین ارزش سفارش</small></div><div><b>۱۶</b><small>موجودی رو به اتمام</small></div></div><div className="admin-grid"><section><h2>افزودن محصول</h2><input placeholder="نام محصول"/><input placeholder="شناسه محصول / SKU"/><textarea placeholder="توضیحات کامل"/><textarea placeholder="توضیح کوتاه"/><input type="file"/><input type="file" multiple/><button className="primary">ثبت محصول</button></section><section><h2>مدیریت فروشگاه</h2><ul><li>دسته‌بندی و برند</li><li>کدهای تخفیف و قیمت خط‌خورده</li><li>موجودی، مالیات و هزینه پست</li><li>مقالات، موضوعات، تگ و تصویر</li><li>تأیید دیدگاه‌ها و فاکتور PDF</li></ul></section></div></main>}
