<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
Schema::create('categories',fn(Blueprint $t)=>$t->id()->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete()->string('name')->string('slug')->unique()->text('description')->nullable()->timestamps());
Schema::create('brands',fn(Blueprint $t)=>$t->id()->string('name')->string('slug')->unique()->string('logo')->nullable()->timestamps());
Schema::create('products',function(Blueprint $t){$t->id();$t->foreignId('category_id')->constrained()->cascadeOnDelete();$t->foreignId('brand_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->string('sku')->unique();$t->text('short_description')->nullable();$t->longText('description')->nullable();$t->string('main_image')->nullable();$t->json('gallery')->nullable();$t->json('attributes')->nullable();$t->decimal('price',14,0);$t->decimal('sale_price',14,0)->nullable();$t->unsignedInteger('stock')->default(0);$t->decimal('weight',8,2)->nullable();$t->string('dimensions')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('product_images',fn(Blueprint $t)=>$t->id()->foreignId('product_id')->constrained()->cascadeOnDelete()->string('path')->unsignedInteger('sort_order')->default(0)->timestamps());
Schema::create('product_specifications',fn(Blueprint $t)=>$t->id()->foreignId('product_id')->constrained()->cascadeOnDelete()->string('key')->text('value')->timestamps());
Schema::create('coupons',fn(Blueprint $t)=>$t->id()->string('code')->unique()->enum('type',['percent','fixed'])->decimal('amount',14,0)->unsignedInteger('usage_limit')->nullable()->unsignedInteger('used_count')->default(0)->timestamp('starts_at')->nullable()->timestamp('expires_at')->nullable()->boolean('is_active')->default(true)->timestamps());
Schema::create('orders',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('number')->unique();$t->enum('status',['pending_payment','processing','pending_review','completed','cancelled','failed','refunded'])->default('pending_payment');$t->enum('shipping_method',['mashhad_courier','pickup','post']);$t->enum('payment_method',['zarinpal','card_to_card']);$t->string('payment_receipt')->nullable();$t->decimal('subtotal',14,0);$t->decimal('discount',14,0)->default(0);$t->decimal('shipping_cost',14,0)->default(0);$t->decimal('tax',14,0)->default(0);$t->decimal('total',14,0);$t->json('address');$t->timestamps();});
Schema::create('order_items',fn(Blueprint $t)=>$t->id()->foreignId('order_id')->constrained()->cascadeOnDelete()->foreignId('product_id')->nullable()->nullOnDelete()->string('name')->string('sku')->decimal('price',14,0)->unsignedInteger('quantity')->timestamps());
Schema::create('articles',fn(Blueprint $t)=>$t->id()->string('title')->string('slug')->unique()->text('excerpt')->nullable()->longText('body')->string('image')->nullable()->string('topic')->nullable()->boolean('is_published')->default(false)->timestamp('published_at')->nullable()->timestamps()); Schema::create('tags',fn(Blueprint $t)=>$t->id()->string('name')->string('slug')->unique()->timestamps()); Schema::create('article_tag',fn(Blueprint $t)=>$t->foreignId('article_id')->constrained()->cascadeOnDelete()->foreignId('tag_id')->constrained()->cascadeOnDelete()->primary(['article_id','tag_id']));
Schema::create('reviews',fn(Blueprint $t)=>$t->id()->foreignId('product_id')->constrained()->cascadeOnDelete()->foreignId('user_id')->constrained()->cascadeOnDelete()->unsignedTinyInteger('rating')->text('body')->boolean('is_approved')->default(false)->timestamps()); Schema::create('store_settings',fn(Blueprint $t)=>$t->id()->string('key')->unique()->text('value')->nullable()->timestamps()); }
public function down():void{Schema::dropIfExists('store_settings');Schema::dropIfExists('reviews');Schema::dropIfExists('article_tag');Schema::dropIfExists('tags');Schema::dropIfExists('articles');Schema::dropIfExists('order_items');Schema::dropIfExists('orders');Schema::dropIfExists('coupons');Schema::dropIfExists('product_specifications');Schema::dropIfExists('product_images');Schema::dropIfExists('products');Schema::dropIfExists('brands');Schema::dropIfExists('categories');}};
